export ANTHROPIC_BASE_URL=http://agentserver.tailda962e.ts.net:8080
export ANTHROPIC_API_KEY=
export ANTHROPIC_MODEL=gemma-4-e4b-it

export ANTHROPIC_DEFAULT_HAIKU_MODEL=gemma-4-e4b-it
export ANTHROPIC_DEFAULT_SONNET_MODEL=gemma-4-e4b-it
export ANTHROPIC_DEFAULT_OPUS_MODEL=gemma-4-e4b-it
export CLAUDE_CODE_SUBAGENT_MODEL=gemma-4-e4b-it

export DISABLE_COMPACT=1
export CLAUDE_CODE_MAX_CONTEXT_TOKENS=131072
export CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS=1
export CLAUDE_CODE_DISABLE_NONSTREAMING_FALLBACK=1
export CLAUDE_CODE_DISABLE_THINKING=1
export MAX_THINKING_TOKENS=0

claude