export ANTHROPIC_BASE_URL=http://agentserver.tailda962e.ts.net:8080

# ====================== LOCAL QWEN CONFIG ======================
# Model
export ANTHROPIC_MODEL=Qwen3.6-35B-A3B-UD-Q3_K_M
export ANTHROPIC_DEFAULT_HAIKU_MODEL=Qwen3.6-35B-A3B-UD-Q3_K_M
export ANTHROPIC_DEFAULT_SONNET_MODEL=Qwen3.6-35B-A3B-UD-Q3_K_M
export ANTHROPIC_DEFAULT_OPUS_MODEL=Qwen3.6-35B-A3B-UD-Q3_K_M
export CLAUDE_CODE_SUBAGENT_MODEL=Qwen3.6-35B-A3B-UD-Q3_K_M


# Context & Behavior
export CLAUDE_CODE_MAX_CONTEXT_TOKENS=131072
export DISABLE_COMPACT=1
export CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS=1
export CLAUDE_CODE_DISABLE_NONSTREAMING_FALLBACK=1
export CLAUDE_CODE_DISABLE_THINKING=1
export MAX_THINKING_TOKENS=0

# ====================== RUN ======================
claude